# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: shagunsodhani
github_username:  shagunsodhani
facebook_username:  shagunsodhani

# Build settings
# markdown: kramdown
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
